# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: idunaver <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/26 15:46:42 by idunaver          #+#    #+#              #
#    Updated: 2018/11/26 18:00:31 by idunaver         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FILE = ./ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -c $(FILE)
	gcc -o $(NAME) *.o
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)
